# Generated by Django 2.2.6 on 2021-02-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_promo_email',
            name='message',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
